[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[options]
packages = [
    "kernel_hardening_checker",
    "kernel_hardening_checker.config_files",
    "kernel_hardening_checker.config_files.defconfigs",
    "kernel_hardening_checker.config_files.distros",
    "kernel_hardening_checker.config_files.kspp-recommendations",
]
include_package_data = true

[tool.setuptools.dynamic]
version = {attr = "kernel_hardening_checker.__version__"}

[project]
name = "kernel-hardening-checker"
requires-python = ">= 3.8"
dynamic = ["version"]
description = "A tool for checking the security hardening options of the Linux kernel"
readme = "README.md"
license = "GPL-3.0-or-later"
license-files = ["LICENSE.txt"]
maintainers = [{ name = "Alexander Popov", email = "alex.popov@linux.com" }]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Topic :: Security",
    "Operating System :: POSIX :: Linux",
    "Environment :: Console",
    "Programming Language :: Python :: 3",
]

[project.scripts]
kernel-hardening-checker = "kernel_hardening_checker:main"

[project.urls]
homepage = "https://github.com/a13xp0p0v/kernel-hardening-checker"
repository = "https://github.com/a13xp0p0v/kernel-hardening-checker"
bugtracker = "https://github.com/a13xp0p0v/kernel-hardening-checker/issues"
