# .woodpecker.yml
steps:
  - name: functional-test-with-coverage
    image: python:3
    when:
      - event: [push, tag, manual]
    commands:
      - ls -la
      - python3 --version
      - python3 -m pip install --upgrade pip
      - python3 -m pip install coverage
      - echo "Run the functional tests and collect coverage..."
      - sh .github/workflows/functional_test.sh
      - echo "Show the coverage report..."
      - coverage report
